# Generated by Django 6.0.3 on 2026-04-07 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('follow_star', 'Follow Star')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0)),
                ('reaction_time', models.FloatField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.gamesession')),
            ],
        ),
    ]
