# Generated by Django 6.0.3 on 2026-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='difficulty_level',
            field=models.CharField(default='Moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(),
        ),
    ]
