# Generated by Django 6.0.3 on 2026-04-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_childprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='final_speed',
            field=models.IntegerField(default=0),
        ),
    ]
