# Generated by Django 6.0.3 on 2026-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metrics_final_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='system_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
