# Generated by Django 6.0.3 on 2026-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metrics_system_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='alert_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
